"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import { usePathname } from "next/navigation";
import { AuthProvider, useAuth } from "./context/AuthContext";
import { useRouter } from "next/router";
import { IUser } from "./models/userModel";
// import { ToastProvider } from "./context/ToastContext";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  return (
    <AuthProvider>
      {/* <ToastProvider> */}
      <html lang="en">
        <body>
          {pathname !== "/login" && pathname !== "/signup" && <Navbar />}
          <div className="pt-20 overflow-y-auto scrollbar-thin scrollbar-thumb-gray-300 scrollbar-track-gray-100">
            {children}
          </div>
        </body>
      </html>
      {/* </ToastProvider> */}
    </AuthProvider>
  );
}
